use std::fs;
use std::path::Path;
use colored::Colorize;

pub async fn controller(name: &str) -> anyhow::Result<()> {
    println!("[*] Generating controller: {}", name.green());
    
    let controllers_dir = Path::new("src/controllers");
    if !controllers_dir.exists() {
        fs::create_dir_all(controllers_dir)?;
    }
    
    let filename = format!("{}.rs", name.to_lowercase());
    let filepath = controllers_dir.join(&filename);
    
    if filepath.exists() {
        println!("{} Controller already exists: {}", "!".yellow(), filename);
        return Ok(());
    }
    
    let pascal_name = to_pascal_case(name);
    
    let content = format!(
r#"//! {} Controller
//! Generated by Yaiko CLI

use yaiko_core::{{Request, Response, StatusCode, json}};

pub async fn list(_req: Request) -> Result<Response, Box<dyn std::error::Error + Send + Sync>> {{
    let items: Vec<serde_json::Value> = vec![];
    Ok(Response::new().json(&json!({{ "{}s": items }}))?)
}}

pub async fn get(req: Request) -> Result<Response, Box<dyn std::error::Error + Send + Sync>> {{
    let id = req.param("id").map(|s| s.as_str()).unwrap_or("0");
    Ok(Response::new().json(&json!({{ "id": id, "message": "{} found" }}))?)
}}

pub async fn create(mut req: Request) -> Result<Response, Box<dyn std::error::Error + Send + Sync>> {{
    let body = req.json().await?;
    Ok(Response::new()
        .status(StatusCode::CREATED)
        .json(&json!({{ "message": "{} created", "{}": body }}))?)
}}

pub async fn update(mut req: Request) -> Result<Response, Box<dyn std::error::Error + Send + Sync>> {{
    let id = req.param("id").map(|s| s.as_str()).unwrap_or("0");
    let body = req.json().await?;
    Ok(Response::new().json(&json!({{ "message": "{} updated", "id": id, "{}": body }}))?)
}}

pub async fn delete(req: Request) -> Result<Response, Box<dyn std::error::Error + Send + Sync>> {{
    let id = req.param("id").map(|s| s.as_str()).unwrap_or("0");
    Ok(Response::new().json(&json!({{ "message": "{} deleted", "id": id }}))?)
}}
"#, pascal_name, name, pascal_name, pascal_name, name, pascal_name, name, pascal_name);
    
    fs::write(&filepath, content)?;
    
    let mod_path = controllers_dir.join("mod.rs");
    let mod_content = if mod_path.exists() {
        fs::read_to_string(&mod_path)?
    } else {
        String::new()
    };
    
    if !mod_content.contains(&format!("pub mod {};", name.to_lowercase())) {
        let new_mod = format!("{}pub mod {};\n", mod_content, name.to_lowercase());
        fs::write(&mod_path, new_mod)?;
    }
    
    println!("[OK] Created: src/controllers/{}", filename);
    println!("  Don't forget to add routes in main.rs!\n");
    
    Ok(())
}

pub async fn model(name: &str) -> anyhow::Result<()> {
    println!("[*] Generating model: {}", name.green());
    
    let models_dir = Path::new("src/models");
    if !models_dir.exists() {
        fs::create_dir_all(models_dir)?;
    }
    
    let filename = format!("{}.rs", name.to_lowercase());
    let filepath = models_dir.join(&filename);
    
    if filepath.exists() {
        println!("{} Model already exists: {}", "!".yellow(), filename);
        return Ok(());
    }
    
    let pascal_name = to_pascal_case(name);
    
    let content = format!(
r#"//! {} Model
//! Generated by Yaiko CLI

use serde::{{Deserialize, Serialize}};
use sqlx::FromRow;
use chrono::{{DateTime, Utc}};

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct {} {{
    pub id: i32,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}}

#[derive(Debug, Deserialize)]
pub struct Create{} {{
    // Add fields for creation
}}

#[derive(Debug, Deserialize)]
pub struct Update{} {{
    // Add optional fields for updates
}}

impl {} {{
    pub async fn all(pool: &sqlx::PgPool) -> Result<Vec<Self>, sqlx::Error> {{
        sqlx::query_as::<_, Self>("SELECT * FROM {}s ORDER BY created_at DESC")
            .fetch_all(pool)
            .await
    }}
    
    pub async fn find(pool: &sqlx::PgPool, id: i32) -> Result<Option<Self>, sqlx::Error> {{
        sqlx::query_as::<_, Self>("SELECT * FROM {}s WHERE id = $1")
            .bind(id)
            .fetch_optional(pool)
            .await
    }}
    
    pub async fn delete(pool: &sqlx::PgPool, id: i32) -> Result<(), sqlx::Error> {{
        sqlx::query("DELETE FROM {}s WHERE id = $1")
            .bind(id)
            .execute(pool)
            .await?;
        Ok(())
    }}
}}
"#, pascal_name, pascal_name, pascal_name, pascal_name, pascal_name, name, name, name);
    
    fs::write(&filepath, content)?;
    
    let mod_path = models_dir.join("mod.rs");
    let mod_content = if mod_path.exists() {
        fs::read_to_string(&mod_path)?
    } else {
        String::new()
    };
    
    if !mod_content.contains(&format!("pub mod {};", name.to_lowercase())) {
        let new_mod = format!("{}pub mod {};\n", mod_content, name.to_lowercase());
        fs::write(&mod_path, new_mod)?;
    }
    
    println!("[OK] Created: src/models/{}", filename);
    println!("  Don't forget to create a migration!\n");
    
    Ok(())
}

pub async fn middleware(name: &str) -> anyhow::Result<()> {
    println!("[*] Generating middleware: {}", name.green());
    
    let middleware_dir = Path::new("src/middleware");
    if !middleware_dir.exists() {
        fs::create_dir_all(middleware_dir)?;
    }
    
    let filename = format!("{}.rs", name.to_lowercase());
    let filepath = middleware_dir.join(&filename);
    
    if filepath.exists() {
        println!("{} Middleware already exists: {}", "!".yellow(), filename);
        return Ok(());
    }
    
    let pascal_name = to_pascal_case(name);
    
    let content = format!(
r#"//! {} Middleware
//! Generated by Yaiko CLI

use yaiko_core::{{Request, Response, Handler, Middleware}};
use async_trait::async_trait;
use std::sync::Arc;

pub struct {};

impl {} {{
    pub fn new() -> Self {{
        {}
    }}
}}

#[async_trait]
impl Middleware for {} {{
    async fn handle(
        &self,
        req: Request,
        next: Arc<dyn Handler>,
    ) -> Result<Response, Box<dyn std::error::Error + Send + Sync>> {{
        tracing::debug!("{} middleware: before");
        let response = next.handle(req).await?;
        tracing::debug!("{} middleware: after");
        Ok(response)
    }}
}}
"#, pascal_name, pascal_name, pascal_name, pascal_name, pascal_name, pascal_name, pascal_name);
    
    fs::write(&filepath, content)?;
    
    let mod_path = middleware_dir.join("mod.rs");
    let mod_content = if mod_path.exists() {
        fs::read_to_string(&mod_path)?
    } else {
        String::new()
    };
    
    if !mod_content.contains(&format!("pub mod {};", name.to_lowercase())) {
        let new_mod = format!("{}pub mod {};\npub use {}::{};\n", 
            mod_content, 
            name.to_lowercase(), 
            name.to_lowercase(),
            pascal_name
        );
        fs::write(&mod_path, new_mod)?;
    }
    
    println!("[OK] Created: src/middleware/{}", filename);
    println!("  Add to your router with .use_middleware({})\n", pascal_name);
    
    Ok(())
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().chain(chars).collect(),
            }
        })
        .collect()
}
